language: node_js
node_js:
  - 12

install:
  - npm ci

before_deploy:
  - bundle install
  - travis_wait 30 make build_production

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  on:
    branch: source
