# Example Site settings

#google_analytics: UA-NNNNNNNN-N

plugins:
  - jekyll-feed
  - jekyll-time-to-read
  - jekyll-sitemap

header_pages:
 - index.md
 - search.md
 - memes.md
 - reaching-out.md
 - radio.md
 - rss.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
#listen_for_clients_preferred_style: true # true or false (default)

author:
  twitter: resynth1943

default_keywords: js,ts,typescript,javascript,development,code,coding

colour: "#9900FF"

lang: en

style: dark

footer:
  'Created with Jekyll, and an extension of the <a href="https://github.com/b2a3e8/jekyll-theme-console">Jekyll Console</a> theme.'

future: true

repository: resynth1943/resynth1943.github.io

exclude:
  - node_modules/
  - pnpm-lock.yaml
  - package*.json
  - Gemfile*
  - "*.gemspec"
  - "LICENSE*"
  - "*.lock"
  - "Makefile*"
  - third_party

keep_files:
  - node_modules/

sass:
  # style: compressed

description: The adventures of Resynth, the JavaScript (99% TypeScript) developer and former YouTuber. Also fighting alongside you until it's acceptable; privacy matters.

markdown: kramdown

social:
  name: resynth1943
  links:
    - https://vis.social/@resynth1943
    - https://twitter.com/resynth1943

defaults:
  - scope:
      path: ""
    values:
      # Twitter cards don't like relative links...
      image: https://resynth1943.now.sh/assets/gengar.png
      sitemap: true

logo: https://resynth1943.now.sh/assets/gengar.png